<?php
/**
 *
 * Code skeleton generated by dia-uml2php5 plugin
 * written by KDO kdo@zpmag.com
 */
namespace blog\model;
class Billet {

	/**
	 *
	 * @var int
	 * @access protected
	 */
	protected  $id;

	/**
	 *
	 * @var string
	 * @access protected
	 */
	protected  $title;

	/**
	 *
	 * @var string
	 * @access protected
	 */
	protected  $container;

	/**
	 *
	 * @var string
	 * @access protected
	 */
	protected  $dateAdd;

	/**
	 *
	 * @var string
	 * @access protected
	 */
	protected  $dateEdit;

	/**
	 *
	 * @var int
	 * @access protected
	 */
	protected  $corbeille;

	/**
	 * @access public
	 * @param array $value
	 * @return void
	 */

	public final  function __construct($value = array()) {
		if (!empty($value))
			{
				$this->hydrate($value);
			}
	}


	/**
	 * @access public
	 * @param array $data
	 * @return void
	 */

	public final  function hydrate($data) {
		foreach ($data as $attribute => $value)
		{
			$methode = 'set'.ucfirst($attribute);

			if (is_callable([$this, $methode]))
			{
				$this->$methode($value);
			}
		}
	}

	//setter//
	/**
	 * @access public
	 * @param int $id
	 * @return void
	 */

	public final  function setId($id) {
		$this->id = (int) $id;
	}


	/**
	 * @access public
	 * @param string $title
	 * @return void
	 */

	public final  function setTitle($title) {
		$this->title = $title;
	}


	/**
	 * @access public
	 * @param string $container
	 * @return void
	 */

	public final  function setContainer($container) {
		$this->container = $container;
	}


	/**
	 * @access public
	 * @param string $dateAdd
	 * @return void
	 */

	public final  function setDateAdd($dateAdd) {
		$this->dateAdd = $dateAdd;
	}


	/**
	 * @access public
	 * @param string $dateEdit
	 * @return void
	 */

	public final  function setDateEdit($dateEdit) {
		$this->dateEdit = $dateEdit;
	}

	/**
	 * @access public
	 * @param int $id
	 * @return void
	 */

	public final  function setCorbeille($corbeille) {
		$this->corbeille = (int) $corbeille;
	}

	//getter//
	/**
	 * @access public
	 * @return int const
	 */

	public final  function id() {
		return $this->id;
	}


	/**
	 * @access public
	 * @return string const
	 */

	public final  function title() {
		return $this->title;
	}


	/**
	 * @access public
	 * @return string const
	 */

	public final  function container() {
		return $this->container;
	}


	/**
	 * @access public
	 * @return string const
	 */

	public final  function dateAdd() {
		return $this->dateAdd;
	}


	/**
	 * @access public
	 * @return string const
	 */

	public final  function dateEdit() {
		return $this->dateEdit;
	}

	/**
	 * @access public
	 * @return int const
	 */

	public final  function corbeille() {
		return $this->corbeille;
	}
}

?>
