<?php
/**
 *
 * Code skeleton generated by dia-uml2php5 plugin
 * written by KDO kdo@zpmag.com
 */
namespace blog\model;
class Signalement {

	/**
	 *
	 * @var int
	 * @access protected
	 */
	protected  $id;

	/**
	 *
	 * @var int
	 * @access protected
	 */
	protected  $idBillet;

	/**
	 *
	 * @var int
	 * @access protected
	 */
	protected  $idAuteur;

	/**
	 *
	 * @var string
	 * @access protected
	 */
	protected  $idCommentaire;

	/**
	 *
	 * @var string
	 * @access protected
	 */
	protected  $dateAjout;

	/**
	 *
	 * @var boolean
	 * @access protected
	 */
	protected  $estNouveau;

	/**
	 *
	 * @var int
	 * @access protected
	 */
	protected  $idSignale;


	/**
	 * @access public
	 * @param array $values
	 * @return void
	 */

	public final  function __construct($values = array()) {
		if (!empty($values))
		{
			$this->hydrate($values);
		}
	}


	/**
	 * @access public
	 * @param array $data
	 * @return void
	 */

	public final  function hydrate($data) {
		foreach ($data as $attribute => $value)
		{
			$methode = 'set'.ucfirst($attribute);

			if (is_callable([$this, $methode]))
			{
				$this->$methode($value);
			}
		}
	}


	/**
	 * @access public
	 * @param int $id
	 * @return void
	 */

	public final  function setId($id) {
		$this->id = (int) $id;
	}


	/**
	 * @access public
	 * @param int $idBillet
	 * @return void
	 */

	public final  function setIdBillet($idBillet) {
		$this->idBillet = (int) $idBillet;
	}


	/**
	 * @access public
	 * @param int $idAuteur
	 * @return void
	 */

	public final  function setIdAuteur($idAuteur) {
		$this->idAuteur = (int) $idAuteur;
	}


	/**
	 * @access public
	 * @param string $idCommentaire
	 * @return void
	 */

	public final  function setIdCommentaire($idCommentaire) {
		$this->idCommentaire = $idCommentaire;
	}


	/**
	 * @access public
	 * @param string $datAjout
	 * @return void
	 */

	public final  function setDateAjout($dateAjout) {
		$this->dateAjout = $dateAjout;
	}


	/**
	 * @access public
	 * @param boolean $estNouveau
	 * @return void
	 */

	public final  function setEstNouveau($estNouveau) {
		$this->estNouveau = $estNouveau;
	}

	/**
	 * @access public
	 * @param int $idSignale
	 * @return void
	 */

	public final  function setIdSignale($idSignale) {
		$this->idSignale = $idSignale;
	}


	/**
	 * @access public
	 * @return int const
	 */

	public final  function id() {
		return $this->id;
	}


	/**
	 * @access public
	 * @return int const
	 */

	public final  function idBillet() {
		return $this->idBillet;
	}


	/**
	 * @access public
	 * @return int const
	 */

	public final  function idAuteur() {
		return $this->idAuteur;
	}


	/**
	 * @access public
	 * @return string const
	 */

	public final  function idCommentaire() {
		return $this->idCommentaire;
	}


	/**
	 * @access public
	 * @return string const
	 */

	public final  function dateAjout() {
		return $this->dateAjout;
	}


	/**
	 * @access public
	 * @return boolean const
	 */

	public final  function estNouveau() {
		return $this->estNouveau;
	}

	/**
	 * @access public
	 * @return int const
	 */

	public final  function idSignale() {
		return $this->idSignale;
	}


}
?>
