<?php
/**
 *
 * Code skeleton generated by dia-uml2php5 plugin
 * written by KDO kdo@zpmag.com
 */
namespace blog\model;
class User {

	/**
	 *
	 * @var int
	 * @access protected
	 */
	protected  $id;

	/**
	 *
	 * @var string
	 * @access protected
	 */
	protected  $pseudo;

	/**
	 *
	 * @var string
	 * @access protected
	 */
	protected  $password;

	/**
	 *
	 * @var string
	 * @access protected
	 */
	protected  $email;

	/**
	 *
	 * @var string
	 * @access protected
	 */
	protected  $date_register;

	/**
	 *
	 * @var string
	 * @access protected
	 */
	protected  $role;


	/**
	 * @access public
	 * @param array $value
	 * @return void
	 */

	public final  function __construct($value = array()) {
		if (!empty($value))
		{
			$this->hydrate($value);
		}
	}


	/**
	 * @access public
	 * @param array $data
	 * @return void
	 */

	public final  function hydrate($data) {
		foreach ($data as $attribute => $value)
		{
			$methode = 'set'.ucfirst($attribute);

			if (is_callable([$this,$methode]))
			{
				$this->$methode($value);
			}
		}
	}


	/**
	 * @access public
	 * @param int $id
	 * @return void
	 */

	public final  function setId($id) {
		$this->id = (int) $id;
	}


	/**
	 * @access public
	 * @param string $pseudo
	 * @return void
	 */

	public final  function setPseudo($pseudo) {
		$this->pseudo = $pseudo;
	}


	/**
	 * @access public
	 * @param string $password
	 * @return void
	 */

	public final  function setPassword($password) {
		$this->password = $password;
	}


	/**
	 * @access public
	 * @param string $email
	 * @return void
	 */

	public final  function setEmail($email) {
		$this->email = $email;
	}


	/**
	 * @access public
	 * @param string $date_register
	 * @return void
	 */

	public final  function setDate_register($date_register) {
		$this->date_register = $date_register;
	}


	/**
	 * @access public
	 * @param string $role
	 * @return void
	 */

	public final  function setrole($role) {
		$this->role = $role;
	}


	/**
	 * @access public
	 * @return int const
	 */

	public final  function id() {
		return $this->id;
	}


	/**
	 * @access public
	 * @return string const
	 */

	public final  function pseudo() {
		return $this->pseudo;
	}


	/**
	 * @access public
	 * @return string const
	 */

	public final  function password() {
		return $this->password;
	}


	/**
	 * @access public
	 * @return string const
	 */

	public final  function email() {
		return $this->email;
	}


	/**
	 * @access public
	 * @return string const
	 */

	public final  function date_register() {
		return $this->date_register;
	}


	/**
	 * @access public
	 * @return string const
	 */

	public final  function role() {
		return $this->role;
	}


}
?>
